version: '3.2'
networks:
  my-network:
    driver: bridge
volumes:
  openldap_data:
    driver: local
  db:
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - "LDAP_ROOT=dc=oleg,dc=com"
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - my-network
  killbill:
    image: killbill/killbill:0.22.26
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
    volumes:
      - C:\Users\Oroma\Desktop\killbill\killbill.properties:/var/lib/killbill/killbill.properties
      - C:\Users\Oroma\Desktop\killbill\logback.xml:/var/lib/killbill/logback.xml
      - C:\Users\Oroma\Desktop\killbill\setenv.sh:/var/lib/tomcat/bin/setenv.sh
      - C:\Users\Oroma\Desktop\killbill\setenv2.sh:/var/lib/tomcat/bin/setenv2.sh
    networks:
      - my-network
  kaui:
    image: killbill/kaui:2.0.9
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
    networks:
      - my-network
  db:
    image: killbill/mariadb:0.22
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
    networks:
      - my-network
